# Generated by Django 2.0.5 on 2018-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('route_shortname', models.CharField(max_length=4)),
                ('route_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=20)),
                ('shape_pt_lat', models.DecimalField(decimal_places=18, max_digits=20)),
                ('shape_pt_lon', models.DecimalField(decimal_places=18, max_digits=20)),
                ('shape_pt_sequence', models.CharField(max_length=5)),
                ('shape_dist_travelled', models.DecimalField(decimal_places=18, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=20)),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.DecimalField(decimal_places=18, max_digits=20)),
                ('stop_lon', models.DecimalField(decimal_places=18, max_digits=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shapes',
            unique_together={('shape_id', 'shape_pt_sequence')},
        ),
    ]
