# Generated by Django 2.0.6 on 2018-08-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dublinBus', '0006_auto_20180802_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lat', models.DecimalField(decimal_places=18, max_digits=20)),
                ('user_lon', models.DecimalField(decimal_places=18, max_digits=20)),
                ('insert_timestamp', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together={('user_id', 'insert_timestamp')},
        ),
    ]
