# Generated by Django 2.0.6 on 2018-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0008_weatherdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdetails',
            name='dewpt',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='weatherdetails',
            name='msl',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='weatherdetails',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='weatherdetails',
            name='vappr',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='weatherdetails',
            name='wetb',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
