# Generated by Django 2.0.6 on 2018-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0009_auto_20180807_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdetails',
            name='rain',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
