# Generated by Django 2.0.6 on 2018-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0010_auto_20180807_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('rain', models.DecimalField(decimal_places=3, max_digits=10)),
                ('temp', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wetb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dewpt', models.DecimalField(decimal_places=3, max_digits=10)),
                ('vappr', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rhum', models.IntegerField()),
                ('msl', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
