# Generated by Django 2.0.6 on 2018-08-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0012_auto_20180807_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoints',
            old_name='user',
            new_name='user_id',
        ),
    ]
